---
stages:
- "statistic"
- "pre"
- "up-stream"
- "env"
- "config"
- "scanner"
- "ut"
- "package"
- "artifact"
- "manifest"
- "publish"
- "specify"
- "e2e"
- "deploy"
- "upgrade"
- "harness"
- "inspect"
- "verify"
- "post"
- "down-stream"
- "notify"
- "external"
before_script:
- "bash\n#定义颜色的变量\nRED_COLOR='\\E[1;31m'   #红\nGREEN_COLOR='\\E[1;32m' #绿\nYELOW_COLOR='\\\
  E[1;33m' #黄\nBLUE_COLOR='\\E[1;34m'  #蓝\nPINK='\\E[1;35m'        #粉红\nEND='\\E[4m'\n\
  #需要使用echo -e\n#echo -e  \"${RED_COLOR}测试内容${END}\"\n#echo -e  \"${YELOW_COLOR}测试\
  内容${END}\"\n#echo -e  \"${BLUE_COLOR}测试内容${END}\"\n# groupPipeLineEnable is Null,\
  \ default is true\nif [ ! -n \"$groupPipeLineEnable\" ] || [ $groupPipeLineEnable\
  \ = true ]; then\n  if [ ! -n \"$projectPipeLineEnable\" ] || [ $projectPipeLineEnable\
  \ = true ]; then\n    echo -e \"${BLUE_COLOR}Begin To Turn Round Pipelines Of project:\
  \ $CI_PROJECT_NAME branch: $CI_COMMIT_REF_SLUG${END}\"\n    echo -e \"${GREEN_COLOR}Let's\
  \ Go.Wish You Success!${END}\"\n  fi\nelse\n  echo -e \"${RED_COLOR}Your Group Pipelines\
  \ Are Disabled.Please Contact Your Group/Project Owners/Maintainers{END}\"\n  exit\
  \ 126\nfi"
".defaultVariables":
  variables:
    GO111MODULE: "on"
    GOPROXY: "http://pip.lenovo.com/repository/go-group/"
    GOSUMDB: "off"
".defaultRules":
  branches:
  - if: "$CI_COMMIT_REF_NAME == \"release-1.1\""
    variables:
      artifactVersion: "1.1"
      packageVersion: "1.1"
      publishVersion: "1.1"
      manifestVersion: "1.1"
      specifyVersion: "1.1"
  - if: "$CI_COMMIT_REF_NAME == \"release-1.5\""
    variables:
      artifactVersion: "1.5"
      packageVersion: "1.5"
      publishVersion: "1.5"
      manifestVersion: "1.5"
      specifyVersion: "1.5"
  - if: "$CI_COMMIT_REF_NAME == \"release-1.6\""
    variables:
      artifactVersion: "1.6"
      packageVersion: "1.6"
      publishVersion: "1.6"
      manifestVersion: "1.6"
      specifyVersion: "1.6"
  - if: "$CI_COMMIT_REF_NAME == \"release-2.0\""
    variables:
      artifactVersion: "2.0"
      packageVersion: "2.0"
      publishVersion: "2.0"
      manifestVersion: "2.0"
      specifyVersion: "2.0"
      postVersion: "2.0"
      updateVersion: "2.0"
  - if: "$CI_COMMIT_REF_NAME == \"release-2.1\""
    variables:
      packageVersion: "2.1"
      artifactVersion: "2.1"
      publishVersion: "2.1"
      manifestVersion: "2.1"
      specifyVersion: "2.1"
      inspectVersion: "2.1"
      harnessVersion: "2.1"
      postVersion: "2.1"
      notifyVersion: "2.1"
      verifyVersion: "2.1"
  - if: "$CI_COMMIT_REF_NAME == \"release-2.2\""
    variables:
      scannerVersion: "2.2"
      packageVersion: "2.2"
      artifactVersion: "2.2"
      publishVersion: "2.2"
      deployVersion: "2.2"
      upgradeVersion: "2.2"
      manifestVersion: "2.2"
      specifyVersion: "2.2"
      inspectVersion: "2.2"
      harnessVersion: "2.2"
      postVersion: "2.2"
      notifyVersion: "2.2"
      verifyVersion: "2.2"
      e2eVersion: "2.2"
  - if: "$CI_COMMIT_REF_NAME == \"release-df\""
    variables:
      packageVersion: "df"
      artifactVersion: "df"
      publishVersion: "df"
      manifestVersion: "df"
      specifyVersion: "df"
      inspectVersion: "df"
      harnessVersion: "df"
      postVersion: "df"
      notifyVersion: "df"
      verifyVersion: "df"
  - if: "$CI_COMMIT_REF_NAME == \"release-light-edge-mini\""
    variables:
      packageVersion: "mini"
      artifactVersion: "mini"
      publishVersion: "mini"
      manifestVersion: "mini"
      specifyVersion: "mini"
      inspectVersion: "mini"
      harnessVersion: "mini"
      postVersion: "mini"
      notifyVersion: "mini"
      verifyVersion: "mini"
  - if: "$CI_COMMIT_REF_NAME == \"release-mepm\""
    variables:
      artifactProjectName: "mepm"
      artifactModuleName: "devops"
      artifactName: "gitlab-ci-template"
      packageFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      packageVersion: "latest"
      artifactFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      artifactVersion: "latest"
      publishFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      publishVersion: "latest"
      manifestFullName: "harbor.lenovo.com/chartrepo/$artifactProjectName"
      manifestVersion: "latest"
      specifyFullName: "harbor.lenovo.com/chartrepo/$artifactProjectName"
      specifyVersion: "latest"
  - if: "$CI_COMMIT_REF_NAME == \"release-cnbu\""
    variables:
      artifactProjectName: "cnbu"
      artifactModuleName: "devops"
      artifactName: "gitlab-ci-template"
      packageFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      packageVersion: "latest"
      artifactFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      artifactVersion: "latest"
      publishFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      publishVersion: "latest"
      manifestFullName: "harbor.lenovo.com/chartrepo/$artifactProjectName"
      manifestVersion: "latest"
      specifyFullName: "harbor.lenovo.com/chartrepo/$artifactProjectName"
      specifyVersion: "latest"
  - if: "$CI_COMMIT_REF_NAME == \"release-1.6-gsc\""
    variables:
      artifactProjectName: "gsc"
      artifactModuleName: "devops"
      artifactName: "gitlab-ci-template"
      packageFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      packageVersion: "latest"
      artifactFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      artifactVersion: "latest"
      publishFullName: "harbor.lenovo.com/$artifactProjectName/$artifactModuleName/$artifactName"
      publishVersion: "latest"
      manifestFullName: "harbor.lenovo.com/chartrepo/$artifactProjectName"
      manifestVersion: "latest"
      specifyFullName: "harbor.lenovo.com/chartrepo/$artifactProjectName"
      specifyVersion: "latest"
  - if: "$CI_COMMIT_REF_NAME == \"release-bodiless\""
    variables:
      scannerVersion: "bodiless"
      packageVersion: "bodiless"
      artifactVersion: "bodiless"
      publishVersion: "bodiless"
      deployVersion: "bodiless"
      upgradeVersion: "bodiless"
      manifestVersion: "bodiless"
      specifyVersion: "bodiless"
      inspectVersion: "bodiless"
      harnessVersion: "bodiless"
      postVersion: "bodiless"
      notifyVersion: "bodiless"
      verifyVersion: "bodiless"
      e2eVersion: "bodiless"
variables:
  annotateVaiables: "Please annotate me, you must not allow to use this key. Warning\
    \ Warning Warning!!!"
  namespace: "default"
  deployment_name: "ssh-exporter"
  project: "harbor.lenovo.com/lecp/oi/ssh-exporter"
  artifacts: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH,$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  release: "latest"
  projectName: "lecp"
  packageName: "$CI_PROJECT_NAME"
  harbor: "http://harbor.lenovo.com"
  DOCKER_HARBOR_USER: "admin"
  DOCKER_HARBOR_PASSWD: "Harbor12345"
  DOCKER_PUSH_IMAGE: "harbor.lenovo.com/lks/cicd/dockerpush:git"
  KUBECTL_TOOL: "harbor.lenovo.com/devel-tool/kubectl_tool:latest"
  mail_list: "zhanghn8@lenovo.com,lengxh@lenovo.com,guozh10@lenovo.com,zhangss20@lenovo.com,lixiang58@lenovo.com"
  project1: "iharbor.lenovo.com/devops/gitlab-ci-template"
  harbor1: "https://iharbor.lenovo.com"
  DOCKER_HARBOR_USER1: "cicd"
  DOCKER_HARBOR_PASSWD1: "Lenovo@123"
  packageFullName: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  packageFullNames: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  packageVersion: "$CI_COMMIT_SHORT_SHA"
  artifactFullName: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  artifactFullNames: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  artifactVersion: "$CI_COMMIT_SHORT_SHA"
  artifactReferenced: "$artifacts"
  manifestFullName: "harbor.lenovo.com/chartrepo/$CI_PROJECT_NAME"
  manifestFullNames: "harbor.lenovo.com/chartrepo/$CI_PROJECT_NAME,harbor.lenovo.com/chartrepo/$CI_PROJECT_NAME"
  manifestVersion: "$CI_COMMIT_SHORT_SHA"
  publishFullName: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  publishFullNames: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  publishVersion: "$CI_COMMIT_SHORT_SHA"
  deployFullName: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  deployFullNames: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  deployVersion: "$CI_COMMIT_SHORT_SHA"
  upgradeFullName: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  upgradeFullNames: "$BASE_REGISTRY_HOST/$CI_PROJECT_PATH"
  upgradeVersion: "$CI_COMMIT_SHORT_SHA"
  specifyFullName: "harbor.lenovo.com/chartrepo/$CI_PROJECT_NAME"
  specifyFullNames: "harbor.lenovo.com/chartrepo/$CI_PROJECT_NAME,harbor.lenovo.com/chartrepo/$CI_PROJECT_NAME"
  specifyVersion: "$CI_COMMIT_SHORT_SHA"
  artifactConfigs: "Dockerfile"
  upStreamPipeline: "https://igitlab.lenovo.com/devops/your-up-stream-pipeline.yml"
  downStreamPipelien: "https://igitlab.lenovo.com/devops/your-down-stream-pipeline.yml"
  annotateMailList: "Please annotate me, you must not allow to use this key. Warning\
    \ Warning Warning!!!"
  mailList: "a@lenovo.com,b@lenovo.com,c@lenovo.com,d@lenovo.com"
  messageTemplate: "Your $CI_COMMIT_SHA for $CI_COMMIT_REF_SLUG of $CI_PROJECT_NAME\
    \ have executed completely.\n Please refer the following information: \n 1、Your\
    \ Up-Stream Pipeline is $upStreamPipeline 2、Your Scanner Report locate at http://isonar.lenovo.com/project/issues?id=$CI_PROJECT_NAME:$CI_PROJECT_ID&resolved=false\
    \ \n 3、Your Unit Test Report locate at http://isonar.lenovo.com/dashboard?id=$CI_PROJECT_NAME:$CI_PROJECT_ID\
    \ \n 4、Your Artifact locate at $publishFullName:$publishVersion \n 5、Your E2e\
    \ Report at {#FixMe} \n 6、Your Artifact is Deployed In $DESTINATION_CLUSTER_IP\
    \ \n 7、Your Inspect Status: $inspectStatus \n 8、Your Deploy Report locate at {#fixme}"
  annotateStatus: "Please annotate me, you must not allow to use this key. Warning\
    \ Warning Warning!!!"
  scannerStatus: "Unknown"
  utStatus: "Unknown"
  packagStatus: "Unknown"
  artifactStatus: "Unknown"
  publishStatus: "Unknown"
  e2eStatus: "Unknown"
  inspectStatus: "Unknown"
  deployStatus: "Unknown"
  upgradeStatus: "Unknown"
  harnessStatus: "Unknown"
  verifyStatus: "Unknown"
  annotateDeployClusterIp: "Please annotate me, you must not allow to use this key.\
    \ Warning Warning Warning!!!"
  destinationClusters: "10.121.12.150"
  destinationHostDomainName: "lb.kubesphere.local"
  annotateBaseImage: "Please annotate me, you must not allow to use this key. Warning\
    \ Warning Warning!!!"
  BASE_REGISTRY_HOST: "harbor.lenovo.com"
  BASE_IMAGE: "harbor.lenovo.com/devel-tool/docker:20.10.5"
  BASE_INIT_IMAGE: "harbor.lenovo.com/base/init:latest"
  BASE_STATISTIC_IMAGE: "harbor.lenovo.com/base/statistic:latest"
  BASE_PRE_IMAGE: "harbor.lenovo.com/base/pre.latest"
  BASE_CONFIG_IMAGE: "harbor.lenovo.com/base/config:latest"
  BASE_ENV_IMAGE: "harbor.lenovo.com/base/env:latest"
  BASE_UT_IMAGE: "harbor.lenovo.com/lecp-base/sonar-py3:py-sonar-go-v3"
  BASE_SCANNER_IMAGE: "harbor.lenovo.com/base/scanner:latest"
  BASE_ARTIFACT_IMAGE: "harbor.lenovo.com/base/artifact-buildx:latest"
  BASE_BUILDKIT_IMAGE: "harbor.lenovo.com/base/buildkit:master-http"
  BASE_UPGRADE_RUNNER_IMAGE: "harbor.lenovo.com/base/upgrade-runner:latest"
  BASE_MANIFEST_IMAGE: "harbor.lenovo.com/base/manifest:latest"
  BASE_PACKAGE_IMAGE: "harbor.lenovo.com/base/package:latest"
  BASE_PUBLISH_IMAGE: "harbor.lenovo.com/base/publish:latest"
  BASE_SPECIFY_IMAGE: "harbor.lenovo.com/base/specify:latest"
  BASE_HARNESS_IMAGE: "harbor.lenovo.com/base/harness:latest"
  BASE_E2E_IMAGE: "harbor.lenovo.com/base/e2e:latest"
  BASE_DEPLOY_IMAGE: "harbor.lenovo.com/base/deploy:latest"
  BASE_UPGRADE_IMAGE: "harbor.lenovo.com/base/upgrade:latest"
  BASE_INSPECT_IMAGE: "harbor.lenovo.com/base/inspect:latest"
  BASE_VERIFY_IMAGE: "harbor.lenovo.com/base/verify:latest"
  BASE_PACKAGE_GO_IMAGE: "harbor.lenovo.com/base/golang:1.15.6"
  BASE_POST_IMAGE: "harbor.lenovo.com/base/post:latest"
  BASE_NOTIFY_IMAGE: "harbor.lenovo.com/base/notify:latest"
  BASE_PACKAGE_PYTHON_IMAGE: ""
  BASE_PACKAGE_JAVA_IMAGE: ""
  BASE_PACKAGE_CLANG_IMAGE: ""
  BASE_PACKAGE_CPLUSPLUS_IMAGE: ""
  BASE_PACKAGE_UT_IMAGE: "harbor.lenovo.com/base/ut:latest"
  BASE_DOCKER_BUILD_IMAGE: "harbor.lenovo.com/base/scanner:latest"
  BASE_MAIL_IMAGE: "harbor.lenovo.com/base/mail:latest"
  BASE_EXTERNAL_IMAGE: "harbor.lenovo.com/base/external:latest"
  annotateProjectMainLanguage: "Please annotate me, you must not allow to use this\
    \ key. Warning Warning Warning!!!"
  BASE_CURRENT_PROJECT_MAIN_LANGUAGE: "UnKnown,Python,Dockerfile"
  BASE_KUBE_CONFIG_PATH: ".gitlab/deploy/.kube/"
  BASE_KUBE_RESOURCE_PATH: ".gitlab/deploy/charts/"
include:
- local: ".gitlab/statistic/statistic.yml"
- local: ".gitlab/pre/pre.yml"
- local: ".gitlab/env/env.yml"
- local: ".gitlab/config/config.yml"
- local: ".gitlab/scanner/scanner.yml"
- local: ".gitlab/ut/ut.yml"
- local: ".gitlab/package/package.yml"
- local: ".gitlab/artifact/artifact.yml"
- local: ".gitlab/manifest/manifest.yml"
- local: ".gitlab/specify/specify.yml"
- local: ".gitlab/e2e/e2e.yml"
- local: ".gitlab/deploy/deploy.yml"
- local: ".gitlab/upgrade/upgrade.yml"
- local: ".gitlab/harness/harness.yml"
- local: ".gitlab/inspect/inspect.yml"
- local: ".gitlab/verify/verify.yml"
- local: ".gitlab/post/post.yml"
- local: ".gitlab/notify/notify.yml"
- local: ".gitlab/external/external.yml"
