nodes:
  - ip: 192.168.1.101
    port: 22
    username: <username>
    password: <password>
  - ip: 192.168.1.102
    port: 22
    username: <username>
    password: <password>

# General metrics configuration; the listed indexes will be collected; the following are all supported indexes.
# 通用指标配置；列出的指标将被采集；下面列出的是支持的所有指标。
metrics:
  - ssh_cpu_utilization
  - ssh_cpu_utilization_user
  - ssh_cpu_utilization_system
  - ssh_cpu_utilization_top5
  - ssh_cpu_percentage_wait
  - ssh_cpu_percentage_idle
  - ssh_cpu_count
  - ssh_memory_utilization
  - ssh_memory_utilization_top5
  - ssh_memory_utilization_swap
  - ssh_memory_available_bytes
  - ssh_memory_available_swap_bytes
  - ssh_disk_utilization
  - ssh_disk_used_bytes
  - ssh_disk_available_bytes
  - ssh_disk_read_bytes_total
  - ssh_disk_write_bytes_total
  - ssh_network_receive_bytes_total
  - ssh_network_transmit_bytes_total

log:
  level: INFO
  output: [file,stream]
  logfile: /var/log/ssh_exporter.log
  datefmt: '%F %T'
  logfmt: '[%(asctime)s] [%(funcName)s.line%(lineno)d] [%(levelname)s] %(message)s'
